name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * 6"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 5
        ascending: true
        stale-issue-message: ''
